<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '1940Joseph....',
  'DATABASE_URL' => 'mysql://groupn9549_app:1940Joseph....@127.0.0.1:3306/groupn9549_dbgroupnj',
  'MAILER_DSN' => 'failover(smtp://info@groupnj1940.com:Joseph@2025....bakou@mx-dc03.ewodi.net)'

  # 'APP_ENV' => 'dev',
  # 'APP_SECRET' => 'groupnj1940....',
  # 'DATABASE_URL' =>'mysql://root:groupnj1940....@127.0.0.1:3306/dbgroupnj',
  # 'MAILER_DSN' => 'failover(smtp://info@groupnj1940.com:Joseph@2025....bakou@mx-dc03.ewodi.net)',
);
